name: Update Font List

on:
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch:

jobs:
    fetch_fonts:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Fetch Fonts
              run: |
                scripts/get_fonts_list.py
              env:
                API_KEY: ${{ secrets.MINIMAL_VUE_SNT_KEY }}

            - name: Check if File Changed
              id: check_file_changed
              run: |
                if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'path/to/your/file'; then
                echo "File has changed."
                echo "::set-output name=file_changed::true"
                else
                echo "File has not changed."
                echo "::set-output name=file_changed::false"
                fi
            
            - name: Update Version in Manifest
              if: steps.check_file_changed.outputs.file_changed == 'true'
              run: |
                scripts/increment_minor_version.py

            - name: Commit and push changes
              if: steps.check_file_changed.outputs.file_changed == 'true'
              run: |
                git config user.name "${{ github.actor }}"
                git config user.email "${{ github.actor }}@users.noreply.github.com"
                git add -A
                git commit -m "Create latest build"
                git push
